CodeForPhilly/paws-data-pipeline

load_paws_data.ipynb
Added the ability to update database tables as new data comes in, eg from pulling data periodically, by dropping a table and recreating it with the new csv
=> added ability to update database tables

requirements.txt
dropped pycrypto from requirements.txt
=> dropped pycrypto from requirements.txt

Dockerfile, src/api_server/api_app.py, src/scripts/sample_script.py, uwsgi.ini
[src] - init src structure
[src] - add basic flask api
[src] - add docker
=> init src structure with basic API

Dockerfile, src/api_server/api_app.py, src/api_server/static/css/app.css, src/api_server/static/js/FileUploader.js, src/api_server/templates/index.html
#31 initial submission. Basic upload works with server side validation and saves csv to the filesystem. Still want to add client side verification and source (pet point, volgisitics, etc) detection.
=> Csv uploader

src/scripts/flow_script.py, src/scripts/match_data.py
Some of the code still needs to be cleaned up, but a matching MVP appears mostly operational.  Per joint debugging session with @urirot tonight.
Next I will try the code in the docker container to test the end-to-end pipeline and output logs and matches for a demo in our weekly meeting.  Once we agree on the output format, it will check one of the remaining boxes left on #44
=> Fix bugs from 29f4af7 and test on real data

requirements.txt, src/datasource_manager.py, src/scripts/load_paws_data.py, src/server/api.py, src/server/file_uploader.py
-Uploader now accepts .xlsx excel files in addition to csvs
-Uploader assumes csvs are in the iso-8859-1 format. This should fix
issues with uploading salesforce data
-Made flask filesystem access thread safe
=> Ehancements to file uploader

src/client/src/App.js, src/client/src/components/Footer.js, src/client/src/components/Forms.js, src/client/src/components/Header.js, src/client/src/pages/About.js, src/client/src/pages/DataView360.js, start_env.sh
=> 360 view ui mock data

src/README.md, src/datasource_manager.py, src/scripts/create_master_df.py, src/scripts/flow_script.py, src/scripts/init_db_schema.py, src/scripts/load_paws_data.py, src/scripts/match_data.py
move data schema to new file - init_db_schema
remove email and name from master table
some other refactoring
=> create db in flow and some refactoring

src/datasource_manager.py, src/scripts/init_db_schema.py, src/scripts/load_paws_data.py, src/server/common_api.py
Changes to enable "insert only" full flow.
=> Create db in flow

src/server/models.py, src/server/pipeline/load_paws_data.py
Implemented updates and used SQL Alchemy model to determine data types of staging dataframe
=> implement updates in pipeline

src/client/src/pages/DataView360/components/SearchBar.js, src/server/api/common_api.py, src/server/config.py, src/server/requirements.txt
Updated the contacts api to split the param on space and perform different search using first and last.  Also, updated the setup to use the docker env to set the database name so we don't use postgres, need to test a bit more.  If I have time, i need create a db user.
=> Feature db config and updated search

src/server/api/file_uploader.py, src/server/datasource_manager.py, src/server/pipeline/load_paws_data.py
modified pipeline to work off the latest import files
=> updated pipeline to handle latest import data

src/client/src/pages/Admin.js, src/client/src/pages/DataView360/components/ContactInfo.js, src/server/api/common_api.py
Added an endpoint to return basic stats per Uri's query
=> add the basics statistics api

src/README.md
Update to src/README.md for issue #137
=> Readme update pointing to wiki

src/server/Dockerfile, src/server/api/admin_api.py, src/server/requirements.txt, src/server/test_api.py
As per Issue #146.   Includes: 
- suggested fix for Issue #147  (404 from /api/statistics)
- Addition of pytest to requirements.txt
- Initial DNS and simple API tests
Sorry about the re-formatting. Can revert and fix if a hassle.
=> Initial changes to support testing

src/server/Dockerfile
Changed contents of dummy `last_execution.json` to keep `Admin.js` happy.
=> Fixed data written in starting last_exec file to keep UI happy

src/client/src/pages/DataView360/components/Adoptions.js, src/client/src/pages/DataView360/components/ContactInfo.js, src/client/src/pages/DataView360/components/Donations.js, src/client/src/pages/DataView360/components/Volunteer.js, src/client/src/pages/DataView360/components/styles/ContactInfo.module.css, src/client/src/pages/DataView360/components/styles/table.css
Fix for bug in "Contact Info" after last UI update.
=> Quick fix for UI

src/server/config.py, src/server/test_api.py
Fixes for testing when running locally (IS_LOCAL==True):
- Creates dummy last_execution.json file (Now same as #148  and #150 when local)
- Skips some of the tests in `test_api.py` that don't make sense when running locally
=> Fixes for testing when running locally

src/server/pipeline/match_data.py
Closes #163 by reducing the roundtrip communication between pandas <-> postgres and output logging frequency.
=> Faster matching

src/client/src/pages/DataView360/DataView360.js, src/client/src/pages/DataView360/components/ContactInfo.js, src/client/src/pages/DataView360/styles/DataView360.module.css
Addressing issue #166:
- Table rows in search results are clickable and link to 360 view
- 360 view includes back button
- Search bar no longer visible on 360 view
=> Search results link to 360 view page

src/server/pipeline/clean_and_load_data.py
Closes #170 
I tested this PR on shifts data, verifying that the Execute button is now idempotent for that table and no longer continuously appends copies of existing records. This commit is untested on donations.
@dcstlouis does this commit fix the issues you were seeing with the duplicate shifts and donations?
=> Deduplicate rows when loading secondary tables

src/server/datasource_manager.py, src/server/requirements.txt
Used the 'phonenumbers' module to normalize the phone numbers we display - issue #165
=> Normalized phone numbers

src/server/Dockerfile, src/server/app.py, src/server/test_api.py, src/server/user_mgmt/base_users.py
Updated `secrets.py` file (in Dropbox secrets folder, mod date 2021-02-18) with new secrets (JWT secret key, base user passwords). 
Pulling base user passwords from that file instead of hard-coding.
Prefixed base usernames (user, editor, admin) -> (base_user, ...) 
Added a number of tests for validating user API behavior.  (For #146 )
Added `--no-reload` to Dockerfile Flask run line.
=> New secrets, new user api tests, prefixed usernames with base_ 

src/server/api/user_api.py, src/server/test_api.py
=> Change login_json to login, update tests

src/client/src/pages/DataView360/DataView360.js, src/client/src/pages/DataView360/components/ContactInfo.js, src/client/src/pages/DataView360/styles/DataView360.module.css, src/server/api/common_api.py
- Adds info to Adoption section
- Displays contact info from salesforcecontacts data as a workaround for Sigel address issue
=> Adoption and ContactInfo updates

src/server/datasource_manager.py
=> Fixed a crash when phone numbers are 1 character long

src/server/pipeline/match_data.py
added mobile to matching following mikes mobile normalization.
also removed a row that doesn't seem to be used and also looks like a python error if it will be.
=> add mobile to matching

src/client/src/pages/DataView360/components/Adoptions.js, src/server/api/common_api.py
remove requests related to events
use date of birth to calculate age
show max 3 pets
=> reduce requests and event data from Adoption table

src/server/datasource_manager.py
=> Removes printing bad phone numbers to stdout

src/client/src/pages/DataView360/DataView360.js, src/client/src/pages/DataView360/components/Volunteer.js, src/client/src/pages/DataView360/components/styles/Volunteer.module.css
Displays volunteer activity data on the 360 view to wrap up issue #166
=> Volunteer activity now included on 360 view

src/server/datasource_manager.py
=> Force 'number' to string in normalize_phone_number()

src/client/default.conf.template, src/client/src/App.js, src/client/src/components/Header.js, src/server/api/admin_api.py, src/server/bin/startServer.sh, src/server/pipeline/match_data.py
forward requests to index.html (fixes refresh on pages that are not home page)
change /upload to /admin
=> fixes and changes for nginx

src/client/src/App.js, src/client/src/pages/Check/Check.js
=> Cleanups and overrides to eliminate npm warnings

.github/workflows/release-containers.yml
This will build the 2 images when we tag the repo v*
=> Create GitHub CI/CD

src/server/datasource_manager.py, src/server/pipeline/clean_and_load_data.py, src/server/pipeline/flow_script.py, src/server/pipeline/match_data.py
Tested a few examples of missed matches are they are now showing the same `matching_id`. Still want to brainstorm to make sure this doesn't have any negative side effects
=> Manual matches

src/server/test_api.py
I'd failed to update tests for /api/listCurrentFiles and
/api/statistics to use Admin JWT
Closes #297
=> Update Admin tests for JWTs

src/client/src/pages/DataView360/View/components/DataTableHeader.js
The makeStyles() function was causing issues in DataTableHeader, which meant that all components using it would trigger the error described in the issue. I removed makeStyles() and added inline styling instead.
=> Bugfix: resolves issue #293

src/server/.dockerignore, src/server/Dockerfile
Resolve https://github.com/CodeForPhilly/paws-data-pipeline/issues/309
=> Fix for #309 to not duplicate files and ignore Dockerfile

src/client/src/pages/DataView360/Search/Search.js, src/server/api/common_api.py
Resolves #312 by ordering the results by last name then first name
=> 312 sort order

src/client/src/components/Header.js
Resolves #324 : Updated "dipslay" to "display"
=> Issue 324: Fixed typo in styling

src/client/src/pages/DataView360/View/components/VolunteerActivity.js
Start date of Volunteer Activity is now in YYYY-MM-DD format. Resolves #339
=> Start date now in YYYY-MM-DD format

src/client/src/pages/DataView360/View/components/ContactInfo.js
=> Show empty contact field instead of null

src/client/src/pages/DataView360/View/View360.js, src/client/src/pages/DataView360/View/components/CollapsibleTable.js, src/client/src/pages/DataView360/View/components/VolunteerActivity.js
Changes "Time" to "Date" in Adoption/Foster records
Adds "years" to age in Adoption/Foster records
Cleans up unused imports
=> Front end cleanup

src/server/api/common_api.py, src/server/datasource_manager.py
We will probably want to run a drop table command against volgisticsshifts so there is no duplication and cross-contamination when shifting the shifts source from the Assignments tab to the Service tab.
=> 358 import correct shifts tab

src/client/src/pages/DataView360/View/components/Donations.js, src/server/api/common_api.py
Resolves issue #353 by sorting by `close_date`
=> Donations section now shows most recent 3 donations

src/client/src/pages/DataView360/View/View360.js, src/client/src/pages/DataView360/View/components/Adoptions.js
Resolves issue #355 by replacing "Breed" with "Adoption Date" and removing history dropdown
=> Adoptions: added adoption date and removed history dropdown

src/server/pipeline/clean_and_load_data.py
@c-simpson These changes might not be necessary if we decide to improve the import process as discussed but are a quick fix.
=> fix dates getting stored as text in the database

src/client/src/utils/utils.js
Pulled out some common functions so they're not redefined in multiple files
=> Common front-end functions

src/server/pipeline/clean_and_load_data.py
Resolves issue with creation of `volgisticsshifts` table (see #371)
=> Fixes issue with creation of volgisticsshifts table

src/client/src/pages/DataView360/View/View360.js, src/client/src/pages/DataView360/View/components/Adoptions.js, src/client/src/pages/DataView360/View/components/Fosters.js, src/server/api/common_api.py
Resolves issue #356 and restores link to Shelterluv page
=> Simplified foster records and restored Shelterluv link

src/server/alembic/versions/e3ef522bd3d9_explicit_create_sfd.py, src/server/api/file_uploader.py, src/server/donations_importer.py, src/server/requirements.txt
This PR
- Adds explicit creation of the **salesforcedonations** table using Alembic
- Adds fuzzy matching on column names from the XLSX file, rejects similarity below threshold
- Does some cleanup for common data problems
- Skips rows without contact_id
- Performs bulk insert into table
- Ensures donation uniqueness by constraint across the ```[opp_id, contact_id, close_date, amount]``` columns
Closes #367 
Closes #368
=> New donations import

src/server/api/common_api.py
`/api/contacts/<search_text>` and `/api/360/<matching_id>`
return RFM score, label and color with all results
=> Returns RFM score, label, color for 360 searches and view

src/client/src/App.js, src/client/src/components/Header.js, src/client/src/pages/DataView360/Search/Search.js, src/client/src/pages/DataView360/View/View360.js, src/client/src/pages/RFM/RFM.js, src/server/alembic/populate_rfm_mapping.sql, src/server/api/common_api.py, src/server/config.py
- rfm_scores and rfm_mapping tables needs to be populated in order for this to work
- in contact search - added column with RFM score and label
- new RFM page added - currently showing 100 results with limit on the API side. limit is optional.
=> Add RFM scores page + in contact search

src/client/src/pages/DataView360/View/components/Adoptions.js, src/server/api/common_api.py
I added the outer loop in `get_animals()` to test all SL ids associated with the matching_id but then I hit an issue in Adoptions.js/getLatestPets() where it's accessing `animal.Events.Time`: 
- Animal #  22538082  appears not to have have any associated  events at SL (imported from old system?) so animal.Events is undefined
I added a check in `getLatestPets()` and if animals.Events or animal.Events.Time is not defined, I return a 1 so that one sorts last . 
I do a similar check in createRows() to return '' for Adoption Date if we don't have it.  
There may be better ways to achieve this - feel free to improve!
Closes #451
=> Gets all animals for matching_id (451)

src/client/src/pages/DataView360/View/components/SupportOverview.js
=> Donations in SupportOverview now padded to 2 decimal places

src/client/package-lock.json
This is an updated version of the `package-lock.json` file, which was created after running `npm audit fix` . This should address outdated dependencies without breaking anything; I tested out the core functionality of the app and everything still works as expected. 
Please check out the branch and test and let me know if you run into any issues. If not, we can merge this and address potentially breaking changes.
=> Result of first npm audit

src/client/src/pages/DataView360/View/View360.js, src/server/api/common_api.py
Removes unused  '/api/animal/<animal_id>/events'  endpoint. 
Adds '/api/last_analysis' endpoint   ->  '2021-12-11T02:29:14.830371'   for #321 
Closes #471
=> Removed unused '/api/animal/<animal_id>/events' endpoint

src/server/pipeline/match_data.py
I checked this running on Docker; updates every 100 rows.
Closes #345
=> Updates exec_status every 100 rows

src/server/api/API_ingest/salesforce_contacts.py
Handles different directories for .pem file depending on run environment.
Prints out total record count in progress.
=> Tweaks to store_contacts_all()

src/server/api/API_ingest/salesforce_contacts.py
Switches Salesforce authentication to JWT flow and adds a test mode when downloading contacts
=> 534-jwt-flow

.gitignore, src/server/api/API_ingest/updated_data.py, src/server/api/internal_api.py
Reverts CodeForPhilly/paws-data-pipeline#548
=> Revert "Revert "510- Salesforce updated contact info""

src/server/Dockerfile, src/server/api/internal_api.py
Clean up mess made from 548 and 549
=> Fix internal_api import,  Dockerfile mkdir

src/client/src/pages/Admin.js
- Updates `Admin` tab with a message to direct users to only upload Volgistics data
- Only renders "Latest Files" section if new files exist (currently it appears `api/listCurrentFiles` is not returning anything).
=> 492: update admin tab UI

src/server/api/internal_api.py
Was added back in 70686c97 but that scoring code has been removed
=> Remove create_scores import again

src/server/api/admin_api.py
Indentation matters - looks like a brain hiccup
Now returns '[]' if no previous runs.
=> Fix 500 error if no previous runs  #565

src/helm-chart/values.yaml
=> Deploy test

src/server/api/common_api.py
=> 569: Fix string interpolation

.gitignore, src/docker-compose.yml
Will close #573 after merging this one
=> Fix docker-compose pg ver,  ignore .pem files

src/server/Dockerfile, src/server/bin/uwsgi.ini
Bumps src-server image to Python 3.10.9
Closes #539
=> update to python 3.10.9

src/server/config.py
Adds check for active connection before db calls
=> 571: Add pool_pre_ping to db engine
