- load_paws_data.ipynb
Implements a proof-of-concept for #9 as a function based on the fuzzywuzzy library.  Finishing the second half of #9 will require some tuning of the fuzzy matching threshold on real names.
This updated code uses the `partial_ratio` function to avoid penalizing nicknames that are substrings.  For example, "Ben" should be a perfect match for "Benjamin."  A standard edit distance calculation would calculate the difference as the deletion of five characters, so allowing partial substring matching is a good alternative.
Aside: if we decide to rewrite our ETL as in-database operations, it looks like many fuzzy string algorithms are included as modules for [PostgreSQL](https://www.postgresql.org/docs/9.1/fuzzystrmatch.html#AEN139557) and …
> Write a function for fuzzy matching

- notebooks/test_fuzzy_match_on_real_data.ipynb
Using an extract from PAWS for volgistics, salesforce, and petpoint data to determine the suitability of the email + fuzzy matched names for joining the data sources together.
From the analysis, it appears that case-insensitive email can match the majority of records from the three datasets.  Fuzzy matching may not be necessary at all: there are ~100 records from each dataset with matching emails but mismatched names, which should be reasonable to manually curate the data and/or flag the matching records by hand (closes #9).  See notebook for additional details and steps for discussion and future work next week.
> [WIP] Test matching rules on PAWS data

- src/datasource_manager.py
- src/scripts/load_paws_data.py
- src/scripts/match_data.py
Cleans up comments and dead code in match_data.py.  Some future PR's will be necessary to handle cases when not all of the data is uploaded simultaneously, rerunning the code when a dataset hasn't changed, etc., but this will at least be cleaner than the previous iteration.
This PR was built on top of #90, so I would recommend merging that one first to see a clearer diff of the changes on this PR.
> Cleanup matching revisited

- src/docker-compose.yml
- src/server/Dockerfile
- src/server/start_server.sh
This is a work-around for the race condition discussed in #180. 
In `docker-compose.yml`, added creation of the `paws` DB at container start.
In the server `Dockerfile`, added a 10s delay before the Alembic operation runs. 
@dkelley we should review how your nginx starup interacts with this in your #175
> Fix for 180: missing  pdp_user_roles table

- src/server/api/user_api.py
`user_api/login_json()` would throw exceptions and 500 errors for badly-formed request bodies. These changes validate that the expected parameters are present and that they are JSON strings. Should either of those tests fail, I added a dummy password hash check so that badly-formed bodies requests take as long to return as well-formed ones.  There's also a dummy_check if username is invalid, since we won't be checking the password. We don't need one if the password was bad becuse we had to run the hash function to find that out.
See Slack #pdp_dev for Postman config to test.
Closes #193
> Improved login robustness

- src/server/models.py
- src/server/pipeline/clean_and_load_data.py
- src/server/pipeline/flow_script.py
Closes #177
The json field in pdp_contacts is now being populated with the original data from the source information from salesforce, volgistics, etc. This will enable queries to extract information from other non-contact fields, such as lifetime volunteer hours, from these primary tables.
For active (non-archived) rows, the binary json field will be updated on every run with the latest version of available data.
> Write original input data to pdp_contacts json

- src/server/app.py
Explicitly set logging level to INFO (most verbose). In Docker, this seems to get set to INFO, but when running it VSCode it seems to be set to WARNING, so we miss a lot of messages.
> Update app.py to set logging level to INFO

- src/server/config.py
- src/server/requirements.txt
Only used to test if 'paws' db exists and to create it if not, but already
being created in docker-compose.yml (since https://github.com/CodeForPhilly/paws-data-pipeline/commit/5367ffeba53c5d59710648fd1f1b2f0d635489ee).
This will allow us to to remove the restriction keeping  SQLAlchemy below 1.4 (once tested).
> Removes use and dependency on sqlalchemy_utils

- src/client/src/App.js
- src/client/src/components/Header.js
- src/client/src/components/Login/Login.js
Restores About link to User header (Uri did to Admin).
Adds new Login header that just has logo and About Link.
Fixed expTime to handle a deleted token.
In App.js, moved <About /> above logged-in check so it is accessible before login. But if not logged-in,  logged-in check still happens and renders  Login at bottom of displayed About page. Fixing may require some ugly conditionals, and we may not care. Maybe add an `<hr>` <hr> at bottom of About page to look intentional?
> Adds AboutUs to User,Login header

- src/server/alembic.ini
- src/server/alembic/env.py
- src/server/api/common_api.py
- src/server/app.py
- src/server/bin/export_secrets.sh
- src/server/bin/startServer.sh
- src/server/pipeline/shelterluv_api_handler.py
- src/server/user_mgmt/base_users.py
Because we can't include `secrets.py` file in public images (#271), added new script `server/bin/export_secrets.sh` that reads secrets file and exports to the environment.  The assumption is than on k8s we'll store secrets and expose as env_vars.
Alembic now gets DB password from environment, no longer hard-coded in `alembic.ini`  (#273)
Server code tries to import as before, then tries to get from environment. (#271)
To test locally
-  Rename `server\secrets.py` to `Xsecrets.py` 
-  Edit `bin\export_secrets.sh` to use that file name
-  Do `down -v` , build, up
-  Watch logs to see Alembic migrations run, base users created
-  Fix filenames!
Q:  Does it make sense to even keep the local import code (possibility of getting out of sync) or should I just set it to get vars from the …
> Improved secrets handling for deployment

- src/server/alembic/versions/f3d30db17bed_change_pdp_users_password_to_bytea.py
- src/server/requirements.txt
'Binary' had been deprecated  a long time in favor of 'LargeBinary', but support for the latter ended at 1.4.
> Updated to support SQL Alchemy 1.4

- src/server/api/admin_api.py
To test , set port in `docker-compose.yml` to something other than 80:
```  client:
build: ./client
container_name: paws-compose-client
ports:
- "8000:80"`
> Redirect to origin, not '/'

- src/server/pipeline/match_data.py
This was an order of operations issue. Below is the pseudo code for the matching logic: 
IF names_matched OR names_reversed_matched AND (email_matches or mobile_matched)
Boolean order of operations is:
1. NOT
2. AND
3. OR
Adding parentheses makes this more clear:
IF names_matched OR (names_reversed_matched AND (email_matches or mobile_matched))
So it was matching if either the names reversed matched and either email or mobile matched or first name and last name matched.
> fix bad matching

- src/client/src/pages/Admin.js
- src/server/api/admin_api.py
Changes  `/api/execute` from HTTP GET  to the more appropriate (and non-retryable) POST.
Closes #325
> Change /api/execute from GET to POST

- src/client/src/pages/DataView360/View/components/Donations.js
- src/client/src/pages/DataView360/View/components/VolunteerHistory.js
- src/server/api/common_api.py
> Issue #327: VolunteerHistory and Donations show most recent 3

- src/client/src/App.js
- src/client/src/components/Header.js
- src/client/src/pages/Login/Logout.js
- src/server/api/user_api.py
Logout.js deletes access_token and redirects to /.
On server, user_logout() gets the username from the JWT.  
As of https://github.com/CodeForPhilly/paws-data-pipeline/commit/ad7412540d22f950848803094131a48a79fb2c72 , the JS is not hitting the API endpoint due to hooks issues. User is logged out, but it's not logged in the user_journal.
Closes #322
> 322 - Quick and dirty logout

- src/server/api/file_uploader.py
If the upload file is badly formatted, an error message appears in the log but it's not easy to spot. This makes it more obvious.
> Makes "No sources found"  log message more obvious 

- src/client/src/pages/DataView360/View/View360.js
- src/client/src/pages/DataView360/View/components/Donations.js
- src/client/src/pages/DataView360/View/components/VolunteerHistory.js
- src/server/alembic/versions/d0841384d5d7_explicitly_create_vshifts.py
- src/server/api/common_api.py
- src/server/api/file_uploader.py
- src/server/datasource_manager.py
- src/server/pipeline/clean_and_load_data.py
- src/server/shifts_importer.py
This builds on PR #382 .
Following 382, it does direct import into the `volgisticsshifts` table. 
There's some clean up for changed column names:
`volgisticsshifts.number` -> `.volg_id`
`volgisticsshifts.from`  - > `.from_date`
Removes Fosters block from 360View as per KF
@sposerina  Please review `datasource_manager.py`   - Looks correct after changes?  Table mappings get used by `clean_and_load_data.py` - would it be better to feed c&l a list instead of it collecting tables from DB?
> Volshifts insert

- src/client/default.conf.template
- src/server/api/api.py
- src/server/api/internal_api.py
- src/server/app.py
Creates /api/internal tree and blocks it from external access.
`http://localhost/api/internal/test`  returns a 404
From another container in the cluster,  `curl http://server:5000/api/internal/test` works
@urirot Can you move your    
`src/server/api/API_ingest/` code into    
`src/server/api/internal/` ?
Closes #396
> Support for /api/internal

- src/server/api/admin_api.py
Quick and dirty import/insert for RFM scores - not production quality
Creates a new admin endpoint:   **/api/import_rfm**  which will import a csv file of   `matching_id, rfm_score` values
Specify the file at line 271  of admin_api.py
When you GET /api/import_rfm , the code reads in the file then passes a list of [mid,score] to the insert function. 
Once loaded, 
```
select  pdpc.matching_id, first_name, last_name, rfm_scores.rfm_score, rfm_label, rfm_color
from pdp_contacts as pdpc
left join rfm_scores on rfm_scores.matching_id = pdpc.matching_id
left join rfm_mapping on rfm_mapping.rfm_value = rfm_scores.rfm_score
LIMIT 50;
```
will show you the results.
We need to figure the best place to put this.
NB: _As matching_ids are not deterministic, this data set is only really useful with the …
> WIP: RFM import

- src/server/alembic/populate_rfm_mapping.sql
- src/server/config.py
- src/server/user_mgmt/base_users.py
Added call to populate_rfm_mapping_table() in config.py with
'overwrite=True' so it loads table at every startup.
Removed BEGIN/COMMIT from script as it runs in a transaction here.
Now you can edit **server/alembic/populate_rfm_mapping.sql** to assign labels/colors/text_colors  to RFM scores. Next server restart, the rfm_mapping table will be populated with your selections. 
Closes #417
> Now populating rfm_mapping table on startup

- src/server/alembic/versions/a3ba63dee8f4_rmv_details_size_limit.py
- src/server/api/admin_api.py
- src/server/pipeline/flow_script.py
to 'error'. This allows another job to be run (which could not happen if  exception was not caught and status was left as 'executing').
Needs UI support (Issue #336 , #229 )  Note that admin_api.py/execute() will return a useful status back to React. We need to check it and tell the user something useful. If there was an error, retrying probably won't help but it should be reported.
Closes #228
> Catches errors in flow_script and sets status (in execution_status table)

- src/client/src/pages/RFM/RFM.js
Fixes #432.  Now, if you pull up the RFM list, click on a name, then click 'Back to Results', you'll return to the RFM list and the names will be there.
> Fixed bug where RFM list was empty upon return from 360 View

- src/server/api/admin_api.py
- src/server/api/internal_api.py
- src/server/pipeline/flow_script.py
- src/server/rfm_funcs/create_scores.py
Moved to internal-only endpoint '/api/test_create_scores'
Non-granular try/except in create_scores() but should keep analysis flow from breaking.
Closes #436
> Adds  exc handling, running scoring after analysis,(436)

- src/README.md
Mine works at 80 and the compose file seems to match 80:80. I think just the readme is maybe out of date.
> doc: Update readme to reflect correct port

- src/helm-chart/templates/deployment.yaml
This is instead of the default Rollling deployment,
which fails because the PVs are RWO, so we have to
kill old server container before starting new.
> Adds deployment strategy: Recreate

- src/server/alembic/generate_rfm_mapping.py
- src/server/api/API_ingest/dropbox_handler.py
- src/server/api/API_ingest/ingest_sources_from_api.py
- src/server/api/API_ingest/shelterluv_api_handler.py
- src/server/api/admin_api.py
- src/server/api/common_api.py
- src/server/api/file_uploader.py
- src/server/api/internal_api.py
- src/server/api/user_api.py
- src/server/app.py
- src/server/config.py
- src/server/donations_importer.py
- src/server/pipeline/flow_script.py
- src/server/pipeline/log_db.py
- src/server/requirements.txt
- src/server/rfm_funcs/create_scores.py
- src/server/shifts_importer.py
- src/server/test_api.py
- src/server/user_mgmt/base_users.py
Setup is in config.py, then available everywhere. Logs to console or stdout as appropriate. 
Changed all `print` statements and `current_app.logger` statements to use `structlog`.
We need to make sure all statements use '%'-type interpolation.
We should review for consistency.
> WIP:Initial version of structured logging for API server

- .gitignore
- src/server/api/user_api.py
Accepts text-based role names for /api/admin/user/update
Closes #525
> Support role names in /api/admin/user/update

- .gitignore
- src/server/api/API_ingest/updated_data.py
- src/server/api/internal_api.py
Adds new internal endpoint `/api/internal/get_updated_data`  
( api/API_ingest/updated_data.py/get_updated_contact_data() ) 
which returns a JSON array of contact info like
```
[
{
contactId: ‘0032g00000Ukx9bAAB’,
personId: ‘1234’,
volgisticsId: 1234,
updatedVolunteerStatus: ‘Active’,
updatedFirstVolunteerDate: 2021/01/01,
updatedLastVolunteerDate: 2021/02/02,
updatedFosterStartDate: 2020/10/18,
updatedFosterEndDate: 2022/01/01
},
]
```
Enables #506 
Closes #510
> 510- Salesforce updated contact info

- src/client/src/pages/UserManagement/Components/Dialog/NewUserDialog.jsx
- src/client/src/pages/UserManagement/Components/Dialog/UpdateUserDialog.jsx
- src/client/src/pages/UserManagement/Components/RolesRadioGroup.jsx
- src/client/src/pages/UserManagement/Validations.js
- src/server/api/user_api.py
- src/server/db_setup/README.md
- src/server/db_setup/base_users.py
Closes #587 
- Removing `editor` role and references to it
- Tweaks password hint message to say "12 characters" instead of "12 letters"
- Updates user/admin choice to radio buttons
- Defaults to user's current role in `UpdateUserDialog` and is blank in `NewUserDialog`
- Fixes bug where new users were being displayed as inactive until page refresh
Reviewers should look for:
- Any missed references to `editor` role
> 587: Tweak new user modal

- src/docker-compose.yml
We'd seen weird connection drops with 13.2.  15.4 seems to fix it.
> Update to use pg 15

- src/helm-chart/values.yaml
- src/server/api/internal_api.py
- src/server/api/pem.py
Fix `values.yaml`
Add to pem path options
Add internal endpoint to start flow for testing
> Misc cleanup

- src/server/pipeline/flow_script.py
Closes https://github.com/CodeForPhilly/paws-data-pipeline/issues/588
- Deletes invalid data from `pdp_contacts` before matching process begins
- It felt cleanest to just delete the data from `pdp_contacts` as a separate step before we start the matching process. I think the ideal would be to never insert these values into `pdp_contacts` to begin with, but I don't think this is very expensive.
> 588: Delete invalid data from pdp_contacts
